name: buildcheck

on:
  pull_request:
  push:
  schedule:
    - cron: 0 3 12 * *

jobs:
  buildcheck:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.24"
          - "1.25"
          - "1.26"

    steps:
      - uses: actions/checkout@v7

      - name: Create Docker Container
        run: |
          docker build . -t manifesting-image --build-arg GO_VERSION=${{ matrix.go }}
          docker run --interactive --detach --volume ${{ github.workspace }}:/app --name manifesting manifesting-image

      - name: Coding Standards
        run: |
          docker exec manifesting goimports -d -e .
          docker exec manifesting test -z "$(goimports -l .)"

      - name: Check Dependencies
        run: docker exec manifesting go mod download

      - name: Unit Tests
        run: docker exec manifesting go test ./... -v -cover
